### ISSUE TITLE
Calculate combined area of buffered pre-clusters and total area of buffered orphans

### ISSUE THREAD

**Issue by Peterak100** [cesaraustralia/GeneticRiskIndex#5]
Two new columns for species database:
1. Total area of buffered pre-clusters
2. Total area of non-clustered orphan records

For some species we are getting too many records that are left as orphans and not being joined to pre-clusters. This indicates an underlying problem with the model for that species - either the dispersal distance assumed needs tweaking, or there has not been sufficient survey effort. Once we have the total area for buffered pre-clusters and buffered orphans we can calculate a ratio. If this ratio is too high (say >50%?) then we can say there is too much uncertainty to make it worth running the model in Circuitscape.

**Comment by rafaqz** [comment]
To clarify, this will be the number of pixels at the given resolution and projection or our raster data, rather than the area. As we only care about proportions, this is easier.
